version: '3.8'
services:
  jenkins:
    image: jenkins-gradle:latest  # O el nombre/versión que uses
    container_name: my-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home  # Montamos un volumen para persistir datos

volumes:
  jenkins_home:
