pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // (Si todavía no has quitado tu bloque de checkout declarativo)
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/main']],
                          userRemoteConfigs: [[url: 'https://github.com/jornkbz/LemonCodeDevOps.git']]])
            }
        }

        stage('Compile') {
            steps {
                dir('CICD/exercises/jenkins-resources/calculator') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew compileJava'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CICD/exercises/jenkins-resources/calculator') {
                    sh './gradlew test'
                }
            }
        }
    }
}

