pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Se hace el checkout de TODO el repo, pero Jenkinsfile está en calculator
                checkout([$class: 'GitSCM', 
                          branches: [[name: '*/main']], 
                          userRemoteConfigs: [[url: 'https://github.com/jornkbz/LemonCodeDevOps.git']]])
            }
        }
        
        stage('Compile') {
            steps {
                sh './gradlew compileJava'
            }
        }
        
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
    }
}
