apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432        # Puerto interno del servicio
      targetPort: 5432  # Puerto del contenedor donde escucha Postgres
